
    <!-- ====== Content Start -->
    <!-- ====== Hero Section Start -->
    <div id="home" class="relative overflow-hidden bg-primary pt-[120px] md:pt-[130px] lg:pt-[160px]" >
      <div class="container">
        <div class="-mx-4 flex flex-wrap items-center">
          <div class="w-full px-4">
            <div class="hero-content wow fadeInUp mx-auto max-w-[780px] text-center" data-wow-delay=".2s" >
              <h1 class="mb-8 text-3xl font-bold leading-snug text-white sm:text-4xl sm:leading-snug md:text-[45px] md:leading-snug" >
                A devil was found lurking (50x)
              </h1>
              <p class="mx-auto mb-10 max-w-[600px] text-base text-[#e4e4e4] sm:text-lg sm:leading-relaxed md:text-xl md:leading-relaxed" >
              I know you were looking for something great, but something went wrong, we will be looking into it for you.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- ====== Hero Section End -->

    <div id="home" class="relative overflow-hidden bg-white pt-[120px] md:pt-[130px] lg:pt-[160px] bottom-8" >
      <div class="container">
        <div class="-mx-4 flex flex-wrap items-center">
          <div class="w-full px-4">
            <div class="hero-content wow fadeInUp mx-auto max-w-[780px] text-center" data-wow-delay=".2s" >
              <img src="assets/images/500.jpg" alt="Kanangra.io 50x error" />
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- ====== Content End -->

