
    <!-- ====== Content Start ====== -->
    <!-- ====== Hero Section Start ====== -->
    <div id="home" class="relative overflow-hidden bg-primary pt-[120px] md:pt-[130px] lg:pt-[160px]" >
      <div class="container">
        <div class="-mx-4 flex flex-wrap items-center">
          <div class="w-full px-4">
            <div class="hero-content wow fadeInUp mx-auto max-w-[780px] text-center" data-wow-delay=".2s" >
              <h1 class="mb-8 text-3xl font-bold leading-snug text-white sm:text-4xl sm:leading-snug md:text-[45px] md:leading-snug" >
                Data Conferences & Summits
              </h1>
              <p class="mx-auto mb-100 max-w-[600px] text-base text-[#e4e4e4] sm:text-lg sm:leading-relaxed md:text-xl md:leading-relaxed" >
              </p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- ====== Hero Section End ====== -->

    <!-- ====== Section Start ======-->
    <section id="id-goes-here" class="bg-[#f3f4fe] pt-20 pb-20 lg:pt-[20px] lg:pb-[20px]" >

      <div class="container px-4">
        <div class="-mx-4 flex flex-wrap items-center">
          <div class="w-full px-4 lg:w-7/12 xl:w-8/12">
            <div class="ud-contact-content-wrapper">
              <div class="ud-contact-title mb-12 lg:mb-[20px]">
              <h2 class="text-3xl font-bold text-dark">
              Upcoming Events
              </h3>
              </div>
              <div class="mb-12 flex flex-wrap justify-between lg:mb-0">
<table class="table-auto">
<tr>
<th class="m-8">Focus</th>
<th class="m-8">Website</th>
<th class="m-8">When</th>
<th class="m-8">Virtual</th>
<th class="m-8">In-person</th>
<th class="m-8">Cost</th>
</th>
<tr>
<td>Data Catalog </td>
<td><a href="https://data.world/events/summit/">data.world Summit</a></td>
<td>Sep 22, 2022</td>
<td>Y</td>
<td>N</td>
<td>Free<td>
</tr>
<tr>
<td>Open Source</td>
<td><a href="https://apachecon.com/">Apache Foundation Conference</a></td>
<td>Oct 3-6 2022</td>
<td>N</td>
<td>Y</td>
<td>$$$</td>
</tr>
<tr>
<td>Event Streaming</td>
<td><a href="https:/currentevent.io/">Confluent Current</a></td>
<td>Oct 4-5 2022</td>
<td>Y</td>
<td>Y</td>
<td>Free and $$$</td>
</tr>
<tr>
<td>Big Data</td>
<td><a href="https://www.ai-expo.net/northamerica/">AI & Big Data Expo</a></td>
<td>Oct 5-6 2022</td>
<td>Y</td>
<td>Y</td>
<td>Free and $$$</td>
</tr>
<tr>
<td>Cloud Provider</td>
<td><a href="https://cloud.withgoogle.com/next">Google Cloud Next</a></td>
<td>Oct 11-13 2022</td>
<td>Y</td>
<td>N</td>
<td>Free</td>
</tr>
<tr>
<td>Data Metrics</td>
<td><a href="https://www.airmeet.com/e/e4530d00-3131-11ed-981a-6f5a72ac6927?preview=true">SaaS Metrics Palooza</a></td>
<td>Oct 11-12 2022</td>
<td>Y</td>
<td>N</td>
<td>Free</td>
</tr>
<tr>
<td>Cloud Provider</td>
<td><a href="https://ignite.microsoft.com/en-US/home">Microsoft Ignite</a></td>
<td>Oct 12-14 2022</td>
<td>?</td>
<td>Y</td>
<td></td>
</tr>
<tr>
<td>Analytics</td>
<td><a href="https://coalesce.getdbt.com/">Coalesce by dbt Labs</a></td>
<td>Oct 17-21 2022</td>
<td>Y</td>
<td>Y</td>
<td>Free and $$$</td>
</tr>
<tr>
<td>Analytics</td>
<td><a href="https://eanalyticsonline.com/">Enterprise Analytics</a></td>
<td>Oct 19 2022</td>
<td>Y</td>
<td>N</td>
<td>Free</td>
</tr>
<tr>
<td>Data Security</td>
<td><a href="https://www.f5.com/company/events/webinars/f5-cybersecurity-summit">F5 Cybersecurity Summit</a></td>
<td>Oct 20 2022</td>
<td>Y</td>
<td>N</td>
<td>Free</td>
</tr>
<tr>
<td>Data Observability</td>
<td><a href="https://impactdatasummit.com/2022">Monte Carlo Impact</a></td>
<td>Oct 25-26 2022</td>
<td>Y</td>
<td>Y</td>
<td>Free and $$$</td>
</tr>
<tr>
<td>Data Pipelines</td>
<td><a href="https://apiworld.co/free-open-pass/">API World 2022 - In Person</a></td>
<td>Oct 25-27 2022</td>
<td>N</td>
<td>Y</td>
<td>$$$</td>
</tr>
<tr>
<td>Data Intelligence</td>
<td><a href="https://citizens.collibra.com/">Collibra Data Citizens</a>
<td>Nov 1-3 2022</td>
<td>N</td>
<td>Y</td>
<td>$$$</td>
</tr>
<tr>
<td>Data Analytics</td>
<td><a href="https://www.influxdays.com/">InfluxDays</a></td>
<td>Nov 2-3 2022</td>
<td>Y</td>
<td>N</td>
<td>Free</td>
</tr>
<tr>
<td>Data Pipelines</td>
<td><a href="https://apiworld.co/free-open-pass/">API World 2022 - Virtual</a></td>
<td>Nov 2-3 2022</td>
<td>Y</td>
<td>N</td>
<td>Free</td>
</tr>
<tr>
<td>Cloud Provider</td>
<td><a href="https://reinvent.awsevents.com/">AWS re:Invent</a></td>
<td>Nov 28 - Dec 2 2022</td>
<td>Y</td>
<td>Y</td>
<td>Free and $$$</td>
</tr>
<tr>
<td>Open Source</td>
<td><a href="https://fosdem.org/2023/news/2022-09-14-fosdem-2023-dates/">FOSDEM</a></td>
<td>Feb 4-5 2023</td>
<td>N</td>
<td>Y</td>
<td>?</td>
</tr>
<tr>
<td>Data and Analytics</td>
<td><a href="https://www.gartner.com/en/conferences/na/data-analytics-us">Gartner Data & Analytics Summit</a></td>
<td>Mar 20 - Mar 22 2023</td>
<td>?</td>
<td>Y</td>
<td>$$$</td>
</tr>
</table>

              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- ====== Section End ====== -->

    <!-- ====== Content Start ====== -->
