
    <!-- ====== Content Start ====== -->
    <!-- ====== Hero Section Start ====== -->
    <div id="home" class="relative overflow-hidden bg-primary pt-[120px] md:pt-[130px] lg:pt-[160px]" >
      <div class="container">
        <div class="-mx-4 flex flex-wrap items-center">
          <div class="w-full px-4">
            <div class="hero-content wow fadeInUp mx-auto max-w-[780px] text-center" data-wow-delay=".2s" >
              <h1 class="mb-8 text-3xl font-bold leading-snug text-white sm:text-4xl sm:leading-snug md:text-[45px] md:leading-snug" >
                Data Conferences & Summits
              </h1>
              <p class="mx-auto mb-100 max-w-[600px] text-base text-[#e4e4e4] sm:text-lg sm:leading-relaxed md:text-xl md:leading-relaxed" >
              </p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- ====== Hero Section End ====== -->

    <!-- ====== Section Start ======-->
    <section id="id-goes-here" class="bg-[#f3f4fe] pt-20 pb-20 lg:pt-[20px] lg:pb-[20px]" >

      <div class="container px-4">
        <div class="-mx-4 flex flex-wrap items-center">
          <div class="w-full px-4 lg:w-7/12 xl:w-8/12">
            <div class="ud-contact-content-wrapper">
              <div class="ud-contact-title mb-12 lg:mb-[20px]">
              </div>
              <div class="mb-12 flex flex-wrap justify-between lg:mb-0">
<table class="table-auto border-separate border-spacing-2 border border-slate-500">
<tr>
<th>Focus</th>
<th>Website</th>
<th>When</th>
<th>Virtual</th>
<th>In-person</th>
<th>Cost</th>
</th>
<tr>
<td>Data Catalog </td>
<td><a href="https://data.world/events/summit/">data.world Summit</a></td>
<td>Sep 22, 2022</td>
<td>Y</td>
<td>N</td>
<td>Free<td>
</tr>
<tr>
<td>Open Source</td>
<td><a href="https://apachecon.com/">Apache Foundation Conference</a></td>
<td>Oct 3 - Oct 6 2022</td>
<td>Y</td>
<td>Y</td>
<td>Free and $$$</td>
</tr>
<tr>
<td>Event Streaming</td>
<td><a href="https:/currentevent.io/">Confluent Current</a></td>
<td>Oct 4-5 2022</td>
<td>Y</td>
<td>Y</td>
<td>Free and $$$</td>
</tr>
<tr>
<td>Cloud Provider</td>
<td><a href="https://ignite.microsoft.com/en-US/home">Microsoft Ignite</a></td>
<td>Oct 12-14 2022</td>
<td>?</td>
<td>Y</td>
<td></td>
</tr>
<tr>
<td>Analytics</td>
<td><a href="https://coalesce.getdbt.com/">Coalesce by dbt Labs</a></td>
<td>Oct 17-21 2022</td>
<td>Y</td>
<td>Y</td>
<td>Free and $$$</td>
</tr>
<tr>
<td>Data Observability</td>
<td><a href="https://impactdatasummit.com/2022">Monte Carlo Impact</a></td>
<td>Oct 25-26 2022</td>
<td>Y</td>
<td>Y</td>
<td>Free and $$$</td>
</tr>
<tr>
<td>Data Intelligence</td>
<td><a href="https://citizens.collibra.com/">Collibra Data Citizens</a>
<td>Nov 1-3 2022</td>
<td>N</td>
<td>Y</td>
<td>$$$</td>
</tr>
<tr>
<td>Cloud Provider</td>
<td><a href="https://reinvent.awsevents.com/">AWS re:Invent</a></td>
<td>Nov 28 - Dec 2 2022</td>
<td>Y</td>
<td>Y</td>
<td>Free and $$$</td>
</tr>
<tr>
<td>Data and Analytics</td>
<td><a href="https://www.gartner.com/en/conferences/na/data-analytics-us">Gartner Data & Analytics Summit</a></td>
<td>Mar 20 - Mar 22 2023</td>
<td>?</td>
<td>Y</td>
<td>$$$</td>
</tr>
</table>

              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- ====== Section End ====== -->

    <!-- ====== Content Start ====== -->
