
    <!-- ====== Content Start ====== -->
    <!-- ====== Hero Section Start ====== -->
    <div id="home" class="relative overflow-hidden bg-primary pt-[120px] md:pt-[130px] lg:pt-[160px]" >
      <div class="container">
        <div class="-mx-4 flex flex-wrap items-center">
          <div class="w-full px-4">
            <div class="hero-content wow fadeInUp mx-auto max-w-[780px] text-center" data-wow-delay=".2s" >
              <h1 class="mb-8 text-3xl font-bold leading-snug text-white sm:text-4xl sm:leading-snug md:text-[45px] md:leading-snug" >
                "Kanangra" means beautiful view.
              </h1>
              <p class="mx-auto mb-10 max-w-[600px] text-base text-[#e4e4e4] sm:text-lg sm:leading-relaxed md:text-xl md:leading-relaxed" >
              At <b>Kanangra.io</b> our goal is to help you create a beautiful view of your data with amazing <b>Data Insights</b>.
              </p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- ====== Hero Section End ====== -->

    <!-- ====== Section Start ====== -->
    <div id="home" class="relative overflow-hidden bg-white  pt-[120px] md:pt-[130px] lg:pt-[160px]" >
      <div class="container">
        <div class="-mx-4 flex flex-wrap items-center">
          <div class="w-full px-4">
            <div class="hero-content wow fadeInUp mx-auto max-w-[780px] text-center" data-wow-delay=".2s" >
              <h2 class="text-3xl font-bold text-dark" >
                Map of Indigenous Australia
              </h2>
              <img src="assets/images/aiatsis-map.jpg " alt="Map of Indigenous Australia - (c) AIATSIS/>
              <p class="mx-auto mb-10 max-w-[600px] text-base sm:text-lg sm:leading-relaxed md:text-xl md:leading-relaxed" >
               Copyright (c) from <a href="https://aiatsis.gov.au/explore/map-indigenous-australia">AIATSIS - The Australian Institute of Aboriginal and Torres Strait Islander Studies</a>
               <br />
               <a href="https://aiatsis.gov.au/sites/default/files/styles/large/public/2020-08/AIATSIS%20map%20of%20Indigenous%20Australia_Copyright%20Australian%20Institute%20of%20Aboriginal%20and%20Torres%20Strait%20Islander%20Studies%202015_Print%20ready%20jpeg.jpg?itok=48updQS8">Original source of image</a>
              </p>
            </div>
            <div class="mx-auto aB[570px]  mb-2">
              <p class="mx-auto mb-10 max-w-[600px] text-base sm:text-lg sm:leading-relaxed md:text-xl md:leading-relaxed" >
                We acknowledge the traditional owners and custodians of country throughout Australia and acknowledge their continuing connection to land, waters and community. We pay our respects to the people, the cultures and the elders past, present and emerging. This website contains no images or voices of deceased people.
</p>
              <p class="mx-auto mb-10 max-w-[600px] text-base sm:text-lg sm:leading-relaxed md:text-xl md:leading-relaxed" >
            Australian First Nations people of Bundjalung were the traditional owners and custodians of our family property "Kanangra", and the people of Dharug were the traditional owners and custodians of the popular named "Kanangra-Boyd National Park". 
</p>
              <p class="mx-auto mb-10 max-w-[600px] text-base sm:text-lg sm:leading-relaxed md:text-xl md:leading-relaxed" >
For more background see <a href="https://en.wikipedia.org/wiki/Indigenous_Australians">Australian First Nations</a>.
</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- ====== Section End ====== -->
    <!-- ====== Content End ====== -->

