    <!-- ====== Content Start ====== -->
    <!-- ====== Hero Section Start ====== -->
    <div id="home" class="relative overflow-hidden bg-primary pt-[120px] md:pt-[130px] lg:pt-[160px]" >
      <div class="container">
        <div class="-mx-4 flex flex-wrap items-center">
          <div class="w-full px-4">
            <div class="hero-content wow fadeInUp mx-auto max-w-[780px] text-center" data-wow-delay=".2s" >
              <h1 class="mb-8 text-3xl font-bold leading-snug text-white sm:text-4xl sm:leading-snug md:text-[45px] md:leading-snug" >
                Data Podcasts
              </h1>
              <p class="mx-auto mb-100 max-w-[600px] text-base text-[#e4e4e4] sm:text-lg sm:leading-relaxed md:text-xl md:leading-relaxed" >
              </p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- ====== Hero Section End ====== -->

    <!-- ====== Section Start ======-->
    <section id="id-goes-here" class="bg-[#f3f4fe] pt-20 pb-20 lg:pt-[20px] lg:pb-[20px]" >

      <div class="container px-4">
        <div class="-mx-4 flex flex-wrap items-center">
          <div class="w-full px-4 lg:w-7/12 xl:w-8/12">
            <div class="ud-contact-content-wrapper">
              <div class="ud-contact-title mb-12 lg:mb-[20px]">
              </div>
              <div class="mb-12 flex flex-wrap justify-between lg:mb-0">
<table class="table-auto">
<tr>
<th class="m-8">Podcast</th>
<th class="m-8">Links</th>
</th>
<tr>
<td nowrap="nowrap">Lights On Data Show</td>
<td nowrap="nowrap"><a href="https://lifeaftergdpr.eu/">Website</a>, <a href="https://twitter.com/georgefirican">Twitter</a>, <a href="https://www.lightsondata.com/lights-on-data-show/feed">RSS</a></td>
</tr>
<tr>
<td nowrap="nowrap">Thoughworks Technology Podcasts</td>
<td nowrap="nowrap"><a href="https://www.thoughtworks.com/en-us/insights/podcasts">Website</a></td>
</tr>
<tr>
<td nowrap="nowrap">Data Radicals</td>
<td nowrap="nowrap"><a href="https://www.alation.com/podcast/">Website</a>, <a href="https://twitter.com/alation">Twitter</a></td>
</tr>
<tr>
<td nowrap="nowrap">Streaming Audio</td>
<td nowrap="nowrap"><a href="https://pod.link/streaming-audio">Website</a>, <a href="https://feeds.buzzsprout.com/186154.rss">RSS</a></td>
</tr>
<tr>
<td nowrap="nowrap">Data Driven Leadership</td>
<td nowrap="nowrap"><a href="https://resultant.com/podcasts/">Website</a></td>
</tr>
<tr>
<td nowrap="nowrap">Data Leadership Lessons</td>
<td nowrap="nowrap"><a href="https://data-leadership-lessons.castos.com/">Website</a>, <a href="https://data-leadership-lessons.castos.com/feed">RSS</a></td>
</tr>
<tr>
<td nowrap="nowrap">Life after GDPR -A Podcast about Digital Marketing & Data Privacy</td>
<td><a href="https://lifeaftergdpr.eu/">Website</a>, <a href="https://twitter.com/LifeAfterGDPR">Twitter</a>, <a href="https://lifeaftergdpr.eu/rss/">RSS</a></td>
</tr>
<tr>
</table>

              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- ====== Section End ====== -->

    <!-- ====== Content Start ====== -->
