    <!-- ====== Content Start ====== -->
    <!-- ====== Hero Section Start ====== -->
    <div id="home" class="relative overflow-hidden bg-primary pt-[120px] md:pt-[130px] lg:pt-[160px]" >
      <div class="container">
        <div class="-mx-4 flex flex-wrap items-center">
          <div class="w-full px-4">
            <div class="hero-content wow fadeInUp mx-auto max-w-[780px] text-center" data-wow-delay=".2s" >
              <h1 class="mb-8 text-3xl font-bold leading-snug text-white sm:text-4xl sm:leading-snug md:text-[45px] md:leading-snug" >
                Data Products
              </h1>
              <p class="mx-auto mb-100 max-w-[600px] text-base text-[#e4e4e4] sm:text-lg sm:leading-relaxed md:text-xl md:leading-relaxed" >
              Uncover the categories of products used in a modern data architecture and some products for each category.
              </p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- ====== Hero Section End ====== -->

    <!-- ====== Section Start ======-->
    <section class="bg-[#f3f4fe] pt-20 pb-20 lg:pt-[20px] lg:pb-[20px]" >

      <div class="container px-4">
        <div class="-mx-4 flex flex-wrap items-center">
          <div class="w-full px-4 lg:w-7/12 xl:w-8/12">
            <div class="ud-contact-content-wrapper">
              <div class="ud-contact-title mb-12 lg:mb-[20px]">
              </div>
              <div class="mb-12 flex flex-wrap justify-between lg:mb-0">
<table class="table-auto w-full">
<th colspan="6" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="cloud">Public Cloud Providers</h2>
</th>
<tr>
<th>Abbreviation</th>
<th>Name</th>
<th>Website</th>
<th>Marketplace</th>
<th>Other References</th>
</tr>
<tr>
<td>AWS</td>
<td class="whitespace-nowrap">Amazon Web Services</div></td>
<td class="whitespace-nowrap"><a href="https://aws.amazon.com/">https://aws.amazon.com/</a></td>
<td><a href="https://aws.amazon.com/marketplace">https://aws.amazon.com/marketplace</a></td>
<td></td>
</tr>
<tr>
<td>GCP</td>
<td class="whitespace-nowrap">Google Cloud Platform</td>
<td><a href="https://cloud.google.com/">https://cloud.google.com/</a></td>
<td><a href="https://cloud.google.com/marketplace">https://cloud.google.com/marketplace</a></td>
<td></td>
</tr>
<tr>
<td>Azure</td>
<td>Microsoft Azure</td>
<td><a href="https://azure.microsoft.com/">https://azure.microsoft.com/</a></td>
<td class="whitespace-nowrap"><a href="https://azuremarketplace.microsoft.com/en-us/home">https://azuremarketplace.microsoft.com/en-us/home</a></td>
<td></td>
<tr>
<td>OCI</td>
<td>Oracle Cloud</td>
<td><a href="https://www.oracle.com/cloud/">https://www.oracle.com/cloud/</a> </td>
<td><a href="https://cloudmarketplace.oracle.com/marketplace/">https://cloudmarketplace.oracle.com/marketplace/</a></td>
<td></td>
<tr>
<td>IBM</td>
<td>IBM Cloud</td>
<td><a href="https://www.ibm.com/cloud">https://www.ibm.com/cloud</a></td>
<td><a href="https://cloud.ibm.com/catalog">https://cloud.ibm.com/catalog</a></td>
<td></td>
<tr>
<td>DO</td>
<td>Digital Ocean</td>
<td><a href="https://www.digitalocean.com/">https://www.digitalocean.com/</a></td>
<td><a href="https://marketplace.digitalocean.com/">https://marketplace.digitalocean.com/</a></td>
<td></td>
</tr>
<tr>
<td>CF</td>
<td>Cloudflare</td>
<td><a href="https://www.cloudflare.com/">https://www.cloudflare.com/</a></td>
<td><a href="https://www.cloudflare.com/apps/">https://www.cloudflare.com/apps/</a></td>
<td></td>
</tr>
<th colspan="6" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="cloud">
Cloud Application Hosting / Cloud Platform Service
</h2>
</th>
<tr>
<th></th>
<th>Name</th>
<th>Website</th>
<th></th>
<th></th>
</tr>
<tr>
<td></td>
<td>Render</td>
<td><a href="https://render.com/">https://render.com/</td>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td>Heroku</td>
<td><a href="https://heroku.com/">https://heroku.com/</td>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td>Vercel</td>
<td><a href="https://vercel.com/">https://vercel.com/</td>
<td></td>
<td></td>
</tr>
</table>

              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- ====== Section End ====== -->
    <section id="data-products" class="bg-[#f3f4fe] pt-20 pb-20 lg:pt-[20px] lg:pb-[20px]" >

      <div class="container px-4">
        <div class="-mx-4 flex flex-wrap items-center">
          <div class="w-full px-4 lg:w-7/12 xl:w-8/12">
            <div class="ud-contact-content-wrapper">
              <div class="ud-contact-title mb-12 lg:mb-[20px]">
              </div>
              <div class="mb-12 flex flex-wrap justify-between lg:mb-0">
<table class="table-auto w-full">
<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="streaming">Event Streaming</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</th>
</tr>
<tr>
<td>Apache Kafka</td>
<td><a href="https://kafka.apache.org/">https://kafka.apache.org/</a></td>
<td><a href="https://github.com/apache/kafka">https://github.com/apache/kafka</a></td>
<td><a href="https://twitter.com/apachekafka">Twitter</a></td>
</tr>
<tr>
<td>Confluent</td>
<td><a href="https://www.confluent.io/">https://www.confluent.io/</a></td>
<td><a href="https://github.com/confluentinc">https://github.com/confluentinc</a></td>
<td><a href="https://training.confluent.io/content">Training</a></td>
</tr>
<tr>
<td>AWS Kinesis</td>
<td><a href="https://aws.amazon.com/kinesis/">https://aws.amazon.com/kinesis/</a></td>
<td>N/A</td>
<td></td>
</tr>
<tr>
<td class="whitespace-nowrap">Azure Event Hub</td>
<td class="whitespace-nowrap"><a href="https://azure.microsoft.com/en-us/products/event-hubs/">https://azure.microsoft.com/en-us/products/event-hubs/</a></td>
<td>N/A</td>
<td><a href="https://learn.microsoft.com/en-us/azure/data-explorer/ingest-data-event-hub-overview">Connections overview</a></td>
</tr>
<tr>
<td class="whitespace-nowrap">GCP Datastream</td>
<td><a href="https://cloud.google.com/datastream">https://cloud.google.com/datastream</a></td>
<td>N/A</td>
<td></td>
</tr>
<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="streaming">Pub/Sub Messaging</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</th>
</tr>
<tr>
<td>Apache Pulsar</td>
<td><a href="https://pulsar.apache.org/">https://pulsar.apache.org/</a></td>
<td><a href="https://github.com/apache/pulsar">https://github.com/apache/pulsar</a></td>
<td></td>
</tr>
<tr>
<td>Google Pub/Sub</td>
<td><a href="https://cloud.google.com/pubsub">https://cloud.google.com/pubsub</a></td>
<td>N/A</td>
<td></td>
</tr>
<tr>
<td>Amazon SQS</td>
<td><a href="https://aws.amazon.com/sqs/">https://aws.amazon.com/sqs/</a></td>
<td>N/A</td>
<td></td>
</tr>
<tr>
<td>StreamNative (Pulsar)</td>
<td><a href="https://streamnative.io/">https://streamnative.io/</a></td>
<td>N/A</td>
<td><a href="https://hub.streamnative.io/">Hub</a></td>
</tr>
<tr>
<td>Pandio (Pulsar)</td>
<td><a href="https://pandio.com/apache-pulsar-as-a-service/">https://pandio.com/apache-pulsar-as-a-service/</a></td>
<td>N/A</td>
<td><a href="https://pandio.com/try-free/">Free Trial</a></td>
</tr>

<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="event">Event Data Format / Binary Encoded Format</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</th>
</tr>
<tr>
<td>Avro</td>
<td><a href="https://avro.apache.org/">https://avro.apache.org/</a></td>
<td><a href="https://github.com/apache/avro">https://github.com/apache/avro</a></td>
<td><a href="https://twitter.com/ApacheAvro">Twitter</a></td>
</tr>
<tr>
<td class="whitespace-nowrap">JSON Schema</td>
<td><a href="https://json-schema.org/">https://json-schema.org/</a></td>
<td><a href="https://github.com/json-schema-org">https://github.com/json-schema-org</a></td>
<td><a href="https://json-schema.slack.com/">Slack</a>, <a href="https://json-schema-validator.herokuapp.com/avro.jsp">Avro to JSON Schema</a></td>
</tr>
<tr>
<td>JSON</td>
<td><a href="https://www.json.org/ ">https://www.json.org/</a></td>
<td>N/A</td>
<td><a href="https://jsonlint.com/">Linter</a></td>
</tr>
<tr>
<td>ProtoBuf</td>
<td class="whitespace-nowrap"><a href="https://developers.google.com/protocol-buffers">https://developers.google.com/protocol-buffers</a></td>
<td><a href="https://github.com/protocolbuffers/protobuf/">https://github.com/protocolbuffers/protobuf/</a></td>
<td></td>
</tr>
<tr>
<td>Thrift</td>
<td class="whitespace-nowrap"><a href="https://thrift.apache.org/">https://thrift.apache.org/</a></td>
<td><a href="https://github.com/apache/thrift">https://github.com/apache/thrift</a></td>
<td></td>
</tr>

<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="event">Runtime Registry</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</th>

<tr>
<td>APIcurio</td>
<td class="whitespace-nowrap"><a href="https://www.apicur.io/registry/">https://www.apicur.io/registry/</a></td>
<td><a href="https://github.com/apicurio/apicurio-registry">https://github.com/apicurio/apicurio-registry</a></td>
<td></td>
</tr>
<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="cdc">Change Data Capture (CDC)</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</th>
</tr>
<tr>
<td>Debezium</td>
<td><a href="https://debezium.io/">https://debezium.io/</a></td>
<td><a href="https://github.com/debezium">https://github.com/debezium</a></td>
<td><a href="https://twitter.com/debezium/">Twitter</a></td>
</tr>

<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="cdc">Event Stream Processing</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</th>
</tr>
<tr>
<td>Apache Flink</td>
<td><a href="https://flink.apache.org/">https://flink.apache.org/</a></td>
<td><a href="https://github.com/apache/flink/">https://github.com/apache/flink/</a></td>
<td></td>
</tr>
<tr>
<td>Apache Beam</td>
<td><a href="https://beam.apache.org/">https://beam.apache.org/</a></td>
<td><a href="https://github.com/apache/beam/">https://github.com/apache/beam/</a></td>
<td></td>
</tr>
<tr>
<td>Hazelcast</td>
<td><a href="https://hazelcast.com/">https://hazelcast.com/</a></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Apache Samza</td>
<td><a href="https://samza.apache.org/">https://samza.apache.org/</a></td>
<td><a href="https://github.com/apache/samza/">https://github.com/apache/samza/</a></td>
<td></td>
</tr>
<tr>
<td>Apache Spark</td>
<td><a href="https://spark.apache.org/">https://spark.apache.org/</a></td>
<td><a href="https://github.com/apache/spark/">https://github.com/apache/spark/</a></td>
<td><a href="https://twitter.com/ApacheSpark">Twitter</a></td>
</tr>
<tr>
<td>Apache Storm</td>
<td><a href="https://storm.apache.org/">https://storm.apache.org/</a></td>
<td><a href="https://github.com/apache/storm/">https://github.com/apache/storm/</a></td>
<td><a href="https://twitter.com/apachestorm">Twitter</a></td>
</tr>
<tr>
<td>RutterStack</td>
<td><a href="https://www.rudderstack.com/">https://www.rudderstack.com/</a</td>
<td></td>
<td><a href="https://twitter.com/RudderStack">Twitter</a></td>
</tr>
<tr>
<td>Striim</td>
<td><a href="https://www.striim.com/">https://www.striim.com/</a></td>
<td></td>
<td><a href="https://go2.striim.com/free-trial">Free Trial</a>, <a href="https://twitter.com/striimteam">Twitter</a></td>
</tr>

<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="pipeline">Real-time Data Processing</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</tr>
<tr>
<td>Decodable</td>
<td><a href="https://www.decodable.co/">https://www.decodable.co/</a></td>
<td></td>
<td><a href="https://twitter.com/decodableco">Twitter</a></td>
</tr>

<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="pipeline">Data Pipelines - Batch Processing</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</tr>
<tr>
<td>Dagster</td>
<td><a href="https://dagster.io/">https://dagster.io/</a></td>
<td><a href="https://github.com/dagster-io/dagster">https://github.com/dagster-io/dagster</a></td>
<td>Slack</td>
</tr>
<tr>
<td>Orchest</td>
<td><a href="https://www.orchest.io/">https://www.orchest.io/</a></td>
<td><a href="https://github.com/orchest/orchest">https://github.com/orchest/orchest</a></td>
<td><a href="https://orchest.slack.com/join/shared_invite/zt-g6wooj3r-6XI8TCWJrXvUnXKdIKU_8w#/shared-invite/email">Slack</a></td>
</tr>
<tr>
<td>Upsolver</td>
<td><a href="https://www.upsolver.com/">https://www.upsolver.com/</a></td>
<td>N/A</td>
<td><a href="https://db.upsolver.com/signup?">Free Trial</a></td>
</tr>
<tr>
<td>Fivetran</td>
<td><a href="https://www.fivetran.com/">https://www.fivetran.com/</a></td>
<td>N/A</td>
<td><a href="https://go.fivetran.com/demo">Demo</a> - 14 day trial</td>
</tr>
<tr>
<td>Apache Airflow</td>
<td><a href="https://airflow.apache.org/">https://airflow.apache.org/</a></td>
<td><a href="https://github.com/apache/airflow/">https://github.com/apache/airflow/</a></td>
<td><a href="https://twitter.com/apacheairflow/">Twitter</a></td>
</tr>
<tr>
<td>Astronomer (Airflow)</td>
<td><a href="https://www.astronomer.io/">https://www.astronomer.io/</a></td>
<td><a href="https://github.com/astronomer">https://github.com/astronomer</a></td>
<td><a href="https://twitter.com/astronomerio">Twitter</a></td>
</tr>
<tr>
<td>Gathr</td>
<td><a href="https://www.gathr.one/">https://www.gathr.one/</a></td>
<td></td>
<td><a href="https://www.gathr.one/plans-pricing/">Free Plan</a>, <a href="https://twitter.com/gathr_one">Twitter</a></td>
</tr>

<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="pipeline">Data Transformation</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</tr>
<tr>
<td>dbt</td>
<td><a href="https://www.getdbt.com/">https://www.getdbt.com/</a></td>
<td><a href="https://github.com/dbt-labs/dbt-core">https://github.com/dbt-labs/dbt-core</a></td>
<td><a href="https://docs.getdbt.com/">Docs</a></td>
</tr>
<tr>
<td>Snowpark</td>
<td><a href="https://www.snowflake.com/snowpark/">https://www.snowflake.com/snowpark/</a>
<td></td>
<td></td>
</tr>

<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="etl">Extract - Transform - Load (ETL)</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</th>
</tr>
<tr>
<td>Matillion</td>
<td><a href="https://www.matillion.com/">https://www.matillion.com/</a></td>
<td>N/A</td>
<td><a href="https://www.matillion.com/lp/general-demo">Demo</a></td>
</tr>
<tr>
<td>Airbyte</td>
<td><a href="https://airbyte.com/">https://airbyte.com/</a></td>
<td><a href="https://github.com/airbytehq/airbyte">https://github.com/airbytehq/airbyte</a></td>
<td><a href="https://airbytehq.slack.com/join/shared_invite/zt-1bx4v2t4m-vhZaQu1OdJTyk1M1nSxjBA#/shared-invite/email">Slack</a></td>
</tr>
<tr>
<td>Hevo</td>
<td><a href="https://hevodata.com/pipeline/">https://hevodata.com/pipeline/</a></td>
<td></td>
<td><a href="https://twitter.com/HevoData">Twitter</a></td>
</tr>
<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="etl"> Data Catalog</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</th>
</tr>
<tr>
<td>data.world</td>
<td><a href="https://data.world/">https://data.world/</a></td>
<td>N/A</td>
<td><a href="https://data.world/pricing">Free Community Version</a></td>
</tr>
<tr>
<td>Alation</td>
<td><a href="https://www.alation.com/">https://www.alation.com/</a></td>
<td>N/A</td>
<td></td>
</tr>
<tr>
<td>Collibra</td>
<td><a href="https://www.collibra.com/">https://www.collibra.com/</a></td>
<td>N/A</td>
<td></td>
</tr>
<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="lineage">Data Lineage</h2>
</th>
</tr>
<tr>
<td>Open Lineage Foundation</td>
<td><a href="https://openlineage.io/">https://openlineage.io/</a></td>
<td><a href="https://github.com/OpenLineage/OpenLineage">https://github.com/OpenLineage/OpenLineage</a></td>
<td><a href="https://openlineage.slack.com/join/shared_invite/zt-oko79982-4bHHhxTUDQ9KXgQWXyWVxg#/shared-invite/email">Slack</a></td>
</tr>
<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="lineage">Data Fabric</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</th>
</tr>
<tr>
<td>Talend</td>
<td><a href="https://www.talend.com/">https://www.talend.com/</a></td>
<td>N/A</td>
<td></td>
</tr>
<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="lineage">Data Storage Format</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</th>
</tr>
<tr>
<td>Parquet</td>
<td><a href="https://parquet.apache.org/">https://parquet.apache.org/</a></td>
<td><a href="https://github.com/apache/parquet-mr/">https://github.com/apache/parquet-mr/</a></td>
<td><a href="https://the-asf.slack.com/">Slack</a>, <a href="https://twitter.com/ApacheParquet">Twitter</a></td>
</tr>
<tr>
<td>Apache Arrow</td>
<td><a href="https://arrow.apache.org/">https://arrow.apache.org/</a></td>
<td><a href="https://github.com/apache/arrow">https://github.com/apache/arrow</a></td>
<td><a href="https://twitter.com/apachearrow">Twitter</a></td>
</tr>
<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="lineage">SQL Query Engine</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</th>
</tr>
<tr>
<td>Apache Iceberg</td>
<td><a href="https://iceberg.apache.org/">https://iceberg.apache.org/</a></td>
<td><a href="https://github.com/apache/iceberg">https://github.com/apache/iceberg</a></td>
<td><a href="https://apache-iceberg.slack.com/join/shared_invite/zt-tlv0zjz6-jGJEkHfb1~heMCJA3Uycrg#/shared-invite/email">Slack</a></td>
</tr>
<tr>
<td>Trino</td>
<td><a href="https://trino.io/">https://trino.io/</a></td>
<td><a href="https://github.com/trinodb/trino">https://github.com/trinodb/trino</a></td>
<td><a href="https://trino.io/slack.html">Slack</a>, <a href="https://twitter.com/trinodb">Twitter</a></td>
</tr>
<tr>
<td>Starburst</td>
<td><a href="https://www.starburst.io/">https://www.starburst.io/</a></td>
<td></td>
<td><a href="https://twitter.com/starburstdata">Twitter</a></td>
</tr>
<tr>
<td>Amazon Athena</td>
<td><a href="https://aws.amazon.com/athena">https://aws.amazon.com/athena</a></td>
<td>N/A</td>
<td></td>
</tr>
<tr>
<td>Pandio (Trino)</td>
<td><a href="https://pandio.com/managed-trino-as-a-service/">https://pandio.com/managed-trino-as-a-service/</a></td>
<td>N/A</td>
<td><a href="https://pandio.com/try-free/">Free Trial</a></td>
</tr>
<tr>
<td>Plywood PlyQL</td>
<td><a href="https://plywood.imply.io/plyql">https://plywood.imply.io/plyql</a></td>
<td><a href="https://github.com/implydata/plyql">https://github.com/implydata/plyql</a></td>
<td>Deprecated due to Druid SQL</td>
</tr>
<tr>
<td class="whitespace-nowrap">Amazon Redshift Spectrum</td>
<td><a href="https://docs.aws.amazon.com/redshift/latest/dg/c-using-spectrum.html">https://docs.aws.amazon.com/redshift/latest/dg/c-getting-started-using-spectrum.html</a></td>
<td>N/A</td>
<td></td>
</tr>
<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="lineage">Data Analytics / Business Intelligence</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</th>
</tr>
<tr>
<td class="whitespace-nowrap">Power BI</td>
<td class="whitespace-nowrap"><a href="https://powerbi.microsoft.com/">https://powerbi.microsoft.com/</a></td>
<td><a href="">N/A</a></td>
<td></td>
</tr>
<tr>
<td class="whitespace-nowrap">Tableau</td>
<td class="whitespace-nowrap"><a href="https://www.tableau.com/">https://www.tableau.com/</a></td>
<td><a href="">N/A</a></td>
<td><a href="https://www.tableau.com/products/trial">Free Trial</a></td>
</tr>
<tr>
<td class="whitespace-nowrap">Looker</td>
<td class="whitespace-nowrap"><a href="https://www.looker.com/">https://www.looker.com/</a></td>
<td></td>
<td>
</tr>
<tr>
<td class="whitespace-nowrap">Siense</td>
<td class="whitespace-nowrap"><a href="https://www.sisense.com/">https://www.sisense.com/</a></td>
<td></td>
<td><a href="https://www.sisense.com/get/free-trial/">Free Trial</a>, Ssense<a href="https://twitter.com/sisense/">Twitter</a></td>
</tr>
<tr>
<td class="whitespace-nowrap">Startree</td>
<td class="whitespace-nowrap"><a href="https://www.startree.ai/">https://www.startree.ai/</a></td>
<td><a href="">N/A</a></td>
<td><a href="https://twitter.com/startreedata">Twitter</a>, <a href="https://communityinviter.com/apps/startreedata/startree-community">Slack</a></td>
</tr>
<tr>
<td class="whitespace-nowrap">Cloudbutton</td>
<td class="whitespace-nowrap"><a href="https://cloudbutton.eu/">https://cloudbutton.eu/</a></td>
<td><a href="https://github.com/cloudbutton">https://github.com/cloudbutton</a></td>
<td><a href="https://twitter.com/cloudbutton2020">Twitter</a></td>
</tr>
<tr>
<td class="whitespace-nowrap">Azure Data Explorer</td>
<td class="whitespace-nowrap"><a href="https://azure.microsoft.com/en-us/products/data-explorer/">https://azure.microsoft.com/en-us/products/data-explorer/</a></td>
<td><a href="">N/A</a></td>
<td><a href="https://learn.microsoft.com/en-us/azure/data-explorer/">Documentation</a>, <a href="https://learn.microsoft.com/en-us/azure/data-explorer/kusto/api/">API</a>, <a href="https://learn.microsoft.com/en-us/azure/data-explorer/ingestion-supported-formats">Data Formats</a></td>
</tr>

<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="management">Data Visualization</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</th>
</tr>
<tr>
<td class="whitespace-nowrap">Observable</td>
<td class="whitespace-nowrap"><a href="https://observablehq.com/">https://observablehq.com/</a></td>
<td><a href="https://github.com/observablehq">https://github.com/observablehq<//a></td>
<td><a href="https://twitter.com/observablehq">Twitter</a></td>
</tr>

<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="management">Data Management</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</th>
</tr>
<tr>
<td>DataOps (Snowflake)</td>
<td><a href="https://www.dataops.live/">https://www.dataops.live/</a></td>
<td><a href=""></a></td>
<td><a href="https://www.dataops.live/dataops-for-dummies-download">eBook</a>, <a href="https://www.dataops.live/dataops-free-trial">Free Trial</a></td>
</tr>

<tr>
<td>Apache Calcite</td>
<td><a href="https://calcite.apache.org/">https://calcite.apache.org/</a></td>
<td></td>
<td><a href="https://twitter.com/ApacheCalcite">Twitter</a></td>
</tr>
<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="datastore">OLAP Data Store</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</th>
</tr>
<tr>
<td>Apache Druid</td>
<td><a href="https://druid.apache.org/">https://druid.apache.org/</a></td>
<td><a href="https://github.com/apache/druid/">https://github.com/apache/druid/</a></td>
<td><a href="https://twitter.com/druidio">https://twitter.com/druidio</a></td>
</tr>
<tr>
<td>Apache Pinot</td>
<td><a href="https://pinot.apache.org/">https://pinot.apache.org/</a></td>
<td><a href="https://github.com/apache/pinot">https://github.com/apache/pinot</a></td>
<td><a href="https://twitter.com/ApachePinot">Twitter</a></td>
</tr>
<tr>
<td>Clickhouse</td>
<td><a href="https://clickhouse.com/">https://clickhouse.com/</a></td>
<td><a href="https://github.com/ClickHouse/ClickHouse">https://github.com/ClickHouse/ClickHouse</a></td>
<td><a href="https://twitter.com/ClickhouseDB">https://twitter.com/ClickhouseDB</a></td>
</tr>
<tr>
<td>SingleStore</td>
<td><a href="https://www.singlestore.com/">https://www.singlestore.com/</a></td>
<td><a href="https://github.com/memsql/">https://github.com/memsql/</a></td>
<td></td>
</tr>

<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="datastore">Storage Service</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</th>
</tr>
<tr>
<td>Apache Bookkeeper</td>
<td><a href="https://bookkeeper.apache.org/">https://bookkeeper.apache.org/</a></td>
<td><a href="https://github.com/apache/bookkeeper/">https://github.com/apache/bookkeeper/</a></td>
<td><a href="https://twitter.com/asfbookkeeper">Twitter</a></td>
</tr>
<tr>
<td>Amazon S3</td>
<td><a href="https://aws.amazon.com/s3/">https://aws.amazon.com/s3/</a></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Google Cloud Storage</td>
<td><a href="https://cloud.google.com/storage">https://cloud.google.com/storage</a></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Azure Blob Storage</td>
<td><a href="https://azure.microsoft.com/en-us/products/storage/blobs/">https://azure.microsoft.com/en-us/products/storage/blobs/</a></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Ceph</td>
<td><a href="https://ceph.io/en/">https://ceph.io/en/</a></td>
<td><a href="https://github.com/ceph/ceph">https://github.com/ceph/ceph</a></td>
<td><a href="https://ceph.io/en/community/">Community</a></td>
</tr>

<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="datastore">NoSQL Database</h2>
</th>
</tr>
<tr>
<td>Apache Cassandra</td>
<td><a href="https://cassandra.apache.org/">https://cassandra.apache.org/</a></td>
<td><a href="https://github.com/apache/cassandra">https://github.com/apache/cassandra</a></td>
<td></td>
</tr>
<tr>
<td>DataStax</td>
<td><a href="https://www.datastax.com/">https://www.datastax.com/</a></td>
<td><a href="https://github.com/datastax/">https://github.com/datastax/</a></td>
<td><a href="https://twitter.com/datastax">Twitter</a></td>
</tr>
<tr>
<td>Amazon DynamoDB</td>
<td><a href="https://aws.amazon.com/dynamodb/">https://aws.amazon.com/dynamodb/</a></td>
<td>N/A</td>
<td></td>
</tr>
<tr>
<td>Asure Cosmos DB</td>
<td><a href="https://azure.microsoft.com/products/cosmos-db/">https://azure.microsoft.com/products/cosmos-db/</a>
<td>N/A</td>
<td></td>
</tr>
<tr>
<td>ScyllaDB</td>
<td><a href="https://www.scylladb.com/">https://www.scylladb.com/</a></td>
<td><a hrer="https://github.com/scylladb/scylladb">https://github.com/scylladb/scylladb</a></td>
<td><a href="https://twitter.com/ScyllaDB">Twitter</a>, <a href="https://scylladb-users.slack.com/join/shared_invite/zt-10aop9lk6-uk4I0jlKwSYgQ6MNpt6j4Q#/shared-invite/email">Slack</a></td>
</tr>

<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="datastore">Time-series Database</h2>
</th>
</tr>
<tr>
<td>Timescale</td>
<td><a href="https://www.timescale.com/">https://www.timescale.com/</a></td>
<td><a href="https://github.com/timescale/timescaledb">https://github.com/timescale/timescaledb</a></td>
<td><a href="https://twitter.com/timescaledb?lang=en">Twitter</a>, <a href="https://slack.timescale.com/">Slack</a></td>
</tr>
<tr>
<td>TempoDB</td>
<td><a href="https://tempo-db.com/">https://tempo-db.com/</a></td>
<td>N/A</td>
<td><a href="https://twitter.com/tempodb">Twitter</a></td>
</tr>
<tr>
<td>InfluxData</td>
<td><a href="https://www.influxdata.com/">https://www.influxdata.com/</a></td>
<td><a href="https://github.com/influxdata">https://github.com/influxdata</a></td>
<td><a href="https://community.influxdata.com/">Community</a></td>
</tr>
<tr>
<td>M3</td>
<td><a href="https://m3db.io/">https://m3db.io/</a></td>
<td><a href="https://github.com/m3db/m3">https://github.com/m3db/m3</a></td>
<td><a href="https://m3db.slack.com/join/shared_invite/enQtNzE1MTg3MzAxMjM0LWZiYzYzOTM2OTE1ZWMyMjliMzA0NDE1OWQ0MjM5YjA0MzJiMWFkYmFkZWFlZjhlMmU1OGNmZTg2YzNkM2ExYjA#/shared-invite/email">Slack</a></td>
</tr>
<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="datastore">Real-time Database</h2>
</th>
</tr>
<tr>
<td>Materialize</td>
<td><a href="https://materialize.com/">https://materialize.com/</a></td>
<td><a href="https://github.com/MaterializeInc/materialize">https://github.com/MaterializeInc/materialize</a></td>
<td><a href="https://twitter.com/materializeinc">Twitter</a></td>
</tr>
<tr>
<td>Imply Polaris</td>
<td><a href="https://imply.io/imply-polaris/">https://imply.io/imply-polaris/</a></td>
<td><a href="https://github.com/implydata">https://github.com/implydata</a></td>
<td><a href="https://www.druidforum.org/">Community</a>, <a href="https://imply.io/polaris-signup">Free Trail</a></td>
</tr>
<tr>
<td>Aerospike</td>
<td><a href="https://aerospike.com/">https://aerospike.com/</a></td>
<td></td>
<td><a href="https://twitter.com/aerospikedb">Twitter</a></td>
</tr>

<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="datastore">In-memory Database</h2>
</th>
</tr>
<tr>
<td>Infinispan</td>
<td><a href="https://infinispan.org/">https://infinispan.org/</a></td>
<td>N/A</td>
<td><a href="https://twitter.com/infinispan">Twitter</a></td>
</tr>

<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="datastore">Data Lake / Data Lakehouse</h2>
</th>
</tr>
<tr>
<td>Databricks</td>
<td><a href="https://www.databricks.com/">https://www.databricks.com/</a></td>
<td>N/A</td>
<td><a href="https://twitter.com/databricks">Twitter</a></td>
</tr>
<tr>
<td>Dremio</td>
<td><a href="https://www.dremio.com/">https://www.dremio.com/</a></td>
<td>N/A</td>
<td>Includes <a href="https://www.dremio.com/pricing/">Free Standard Edition</a> </td>
</tr>

<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="datastack">Data Stack</h2>
</th>
<tr>
<td>Keboola</td>
<td><a href="https://www.keboola.com/">https://www.keboola.com/</a></td>
<td>N/A</td>
<td><a href="https://www.keboola.com/">Twitter</a></td>
</tr>
</tr>
<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="datastore">Reverse ETL</h2>
</th>
<tr>
<td>Census</td>
<td><a href="https://www.getcensus.com/">https://www.getcensus.com/</a></td>
<td>N/A</td>
<td>Includes <a href="https://www.getcensus.com/pricing">Free Edition</a> </td>
</tr>
</tr>
<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="datastore">Data Cleansing</h2>
<tr>
<td>Astera</td>
<td><a href="https://discover.astera.com/">https://discover.astera.com/</a></td>
<td>N/A</td>
<td><a href="https://twitter.com/AsteraSoftware">Twitter</a></td>
</tr>
</th>
<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="datastore">Data Insights</h2>
<tr>
<td>Accern (NLP)</td>
<td><a href="https://accern.com/">https://accern.com/</a></td>
<td>N/A</td>
<td></td>
</tr>
<tr>
<td>Snowplow</td>
<td><a href="https://snowplow.io/">https://snowplow.io/</a>
<td>N/A</td>
<td><a href="https://twitter.com/snowplow">Twitter</a></td>
</tr>
</th>
</tr>
</table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- ====== Section End ====== -->

