    <!-- ====== Content Start ====== -->
    <!-- ====== Hero Section Start ====== -->
    <div id="home" class="relative overflow-hidden bg-primary pt-[120px] md:pt-[130px] lg:pt-[160px]" >
      <div class="container">
        <div class="-mx-4 flex flex-wrap items-center">
          <div class="w-full px-4">
            <div class="hero-content wow fadeInUp mx-auto max-w-[780px] text-center" data-wow-delay=".2s" >
              <h1 class="mb-8 text-3xl font-bold leading-snug text-white sm:text-4xl sm:leading-snug md:text-[45px] md:leading-snug" >
                Data Products
              </h1>
              <p class="mx-auto mb-100 max-w-[600px] text-base text-[#e4e4e4] sm:text-lg sm:leading-relaxed md:text-xl md:leading-relaxed" >
              Uncover the categories of products used in a modern data architecture and some products for each category.
              </p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- ====== Hero Section End ====== -->

    <!-- ====== Section Start ======-->
    <section class="bg-[#f3f4fe] pt-20 pb-20 lg:pt-[20px] lg:pb-[20px]" >

      <div class="container px-4">
        <div class="-mx-4 flex flex-wrap items-center">
          <div class="w-full px-4 lg:w-7/12 xl:w-8/12">
            <div class="ud-contact-content-wrapper">
              <div class="ud-contact-title mb-12 lg:mb-[20px]">
              </div>
              <div class="mb-12 flex flex-wrap justify-between lg:mb-0">
<table class="table-auto w-full">
<th colspan="6" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="cloud">Public Cloud Providers</h2>
</th>
<tr>
<th>Abbreviation</th>
<th>Name</th>
<th>Website</th>
<th>Marketplace</th>
<th>Other References</th>
</th>
<tr>
<td>AWS</td>
<td class="whitespace-nowrap">Amazon Web Services</div></td>
<td class="whitespace-nowrap"><a href="https://aws.amazon.com/">https://aws.amazon.com/</a></td>
<td><a href="https://aws.amazon.com/marketplace">https://aws.amazon.com/marketplace</a></td>
<td></td>
</tr>
<tr>
<td>GCP</td>
<td class="whitespace-nowrap">Google Cloud Platform</td>
<td><a href="https://cloud.google.com/">https://cloud.google.com/</a></td>
<td><a href="https://cloud.google.com/marketplace">https://cloud.google.com/marketplace</a></td>
<td></td>
</tr>
<tr>
<td>Azure</td>
<td>Microsoft Azure</td>
<td><a href="https://azure.microsoft.com/">https://azure.microsoft.com/</a></td>
<td class="whitespace-nowrap"><a href="https://azuremarketplace.microsoft.com/en-us/home">https://azuremarketplace.microsoft.com/en-us/home</a></td>
<td></td>
<tr>
<td>OCI</td>
<td>Oracle Cloud</td>
<td><a href="https://www.oracle.com/cloud/">https://www.oracle.com/cloud/</a> </td>
<td><a href="https://cloudmarketplace.oracle.com/marketplace/">https://cloudmarketplace.oracle.com/marketplace/</a></td>
<td></td>
<tr>
<td>IBM</td>
<td>IBM Cloud</td>
<td><a href="https://www.ibm.com/cloud">https://www.ibm.com/cloud</a></td>
<td><a href="https://cloud.ibm.com/catalog">https://cloud.ibm.com/catalog</a></td>
<td></td>
<tr>
<td>DO</td>
<td>Digital Ocean</td>
<td><a href="https://www.digitalocean.com/">https://www.digitalocean.com/</a></td>
<td><a href="https://marketplace.digitalocean.com/">https://marketplace.digitalocean.com/</a></td>
<td></td>
</tr>
<tr>
<td>CF</td>
<td>Cloudflare</td>
<td><a href="https://www.cloudflare.com/">https://www.cloudflare.com/</a></td>
<td><a href="https://www.cloudflare.com/apps/">https://www.cloudflare.com/apps/</a></td>
<td></td>
</tr>
</table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- ====== Section End ====== -->
    <section id="data-products" class="bg-[#f3f4fe] pt-20 pb-20 lg:pt-[20px] lg:pb-[20px]" >

      <div class="container px-4">
        <div class="-mx-4 flex flex-wrap items-center">
          <div class="w-full px-4 lg:w-7/12 xl:w-8/12">
            <div class="ud-contact-content-wrapper">
              <div class="ud-contact-title mb-12 lg:mb-[20px]">
              </div>
              <div class="mb-12 flex flex-wrap justify-between lg:mb-0">
<table class="table-auto w-full">
<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="streaming">Event Streaming - Pub/Sub Messaging</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</th>
</tr>
<tr>
<td>Apache Kafka</td>
<td><a href="https://kafka.apache.org/">https://kafka.apache.org/</a></td>
<td><a href="https://github.com/apache/kafka">https://github.com/apache/kafka</a></td>
<td></td>
</tr>
<tr>
<td>Apache Pulsar</td>
<td><a href="https://pulsar.apache.org/">https://pulsar.apache.org/</a></td>
<td><a href="https://github.com/apache/pulsar">https://github.com/apache/pulsar</a></td>
<td></td>
</tr>
<tr>
<td>Confluent</td>
<td><a href="https://www.confluent.io/">https://www.confluent.io/</a></td>
<td><a href="https://github.com/confluentinc">https://github.com/confluentinc</a></td>
<td><a href="https://training.confluent.io/content">Training</a></td>
</tr>
<tr>
<td>AWS Kinesis</td>
<td><a href="https://aws.amazon.com/kinesis/">https://aws.amazon.com/kinesis/</a></td>
<td>N/A</td>
<td></td>
</tr>
<tr>
<td class="whitespace-nowrap">Azure Event Hub</td>
<td class="whitespace-nowrap"><a href="https://azure.microsoft.com/en-us/products/event-hubs/">https://azure.microsoft.com/en-us/products/event-hubs/</a></td>
<td>N/A</td>
<td><a href="https://learn.microsoft.com/en-us/azure/data-explorer/ingest-data-event-hub-overview">Connections overview</a></td>
</tr>
<tr>
<td class="whitespace-nowrap">GCP Datastream</td>
<td><a href="https://cloud.google.com/datastream">https://cloud.google.com/datastream</a></td>
<td>N/A</td>
<td></td>
</tr>
<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="event">Event Data Format / Binary Encoded Format</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</th>
</tr>
<tr>
<td>Avro</td>
<td><a href="https://avro.apache.org/">https://avro.apache.org/</a></td>
<td><a href="https://github.com/apache/avro">https://github.com/apache/avro</a></td>
<td><a href="https://twitter.com/ApacheAvro">Twitter</a></td>
</tr>
<tr>
<td class="whitespace-nowrap">JSON Schema</td>
<td><a href="https://json-schema.org/">https://json-schema.org/</a></td>
<td><a href="https://github.com/json-schema-org">https://github.com/json-schema-org</a></td>
<td><a href="https://json-schema.slack.com/">Slack</a>, <a href="https://json-schema-validator.herokuapp.com/avro.jsp">Avro to JSON Schema</a></td>
</tr>
<tr>
<td>JSON</td>
<td><a href="https://www.json.org/ ">https://www.json.org/</a></td>
<td>N/A</td>
<td><a href="https://jsonlint.com/">Linter</a></td>
</tr>
<tr>
<td>ProtoBuf</td>
<td class="whitespace-nowrap"><a href="https://developers.google.com/protocol-buffers">https://developers.google.com/protocol-buffers</a></td>
<td><a href="https://github.com/protocolbuffers/protobuf/">https://github.com/protocolbuffers/protobuf/</a></td>
<td></td>
</tr>
<tr>
<td>Thrift</td>
<td class="whitespace-nowrap"><a href="https://thrift.apache.org/">https://thrift.apache.org/</a></td>
<td><a href="https://github.com/apache/thrift">https://github.com/apache/thrift</a></td>
<td></td>
</tr>
<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="cdc">Change Data Capture (CDC)</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</th>
</tr>
<tr>
<td>Debezium</td>
<td><a href="https://debezium.io/">https://debezium.io/</a></td>
<td><a href="https://github.com/debezium">https://github.com/debezium</a></td>
<td><a href="https://twitter.com/debezium/">Twitter</a></td>
</tr>
<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="pipeline">Data Pipelines</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</tr>
<tr>
<td>dbt</td>
<td><a href="https://www.getdbt.com/">https://www.getdbt.com/</a></td>
<td><a href="https://github.com/dbt-labs/dbt-core">https://github.com/dbt-labs/dbt-core</a></td>
<td><a href="https://docs.getdbt.com/">Docs</a></td>
</tr>
<tr>
<td>Orchest</td>
<td><a href="https://www.orchest.io/">https://www.orchest.io/</a></td>
<td><a href="https://github.com/orchest/orchest">https://github.com/orchest/orchest</a></td>
<td><a href="https://orchest.slack.com/join/shared_invite/zt-g6wooj3r-6XI8TCWJrXvUnXKdIKU_8w#/shared-invite/email">Slack</a></td>
</tr>
<tr>
<td>Upsolver</td>
<td><a href="https://www.upsolver.com/">https://www.upsolver.com/</a></td>
<td>N/A</td>
<td><a href="https://db.upsolver.com/signup?">Free Trial</a></td>
</tr>
<tr>
<td>Fivetran</td>
<td><a href="https://www.fivetran.com/">https://www.fivetran.com/</a></td>
<td>N/A</td>
<td><a href="https://go.fivetran.com/demo">Demo</a> - 14 day trial</td>
</tr>
<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="etl">Extract - Transform - Load (ETL)</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</th>
</tr>
<tr>
<td>Matillion</td>
<td><a href="https://www.matillion.com/">https://www.matillion.com/</a></td>
<td>N/A</td>
<td><a href="https://www.matillion.com/lp/general-demo">Demo</a></td>
</tr>
<tr>
<td>Airbyte</td>
<td><a href="https://airbyte.com/">https://airbyte.com/</a></td>
<td><a href="https://github.com/airbytehq/airbyte">https://github.com/airbytehq/airbyte</a></td>
<td><a href="https://airbytehq.slack.com/join/shared_invite/zt-1bx4v2t4m-vhZaQu1OdJTyk1M1nSxjBA#/shared-invite/email">Slack</a></td>
</tr>
<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="etl"> Data Catalog</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</th>
</tr>
<tr>
<td>data.world</td>
<td><a href="https://data.world/">https://data.world/</a></td>
<td>N/A</td>
<td><a href="https://data.world/pricing">Free Community Version</a></td>
</tr>
<tr>
<td>Alation</td>
<td><a href="https://www.alation.com/">https://www.alation.com/</a></td>
<td>N/A</td>
<td></td>
</tr>
<tr>
<td>Collibra</td>
<td><a href="https://www.collibra.com/">https://www.collibra.com/</a></td>
<td>N/A</td>
<td></td>
</tr>
<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="lineage">Data Lineage</h2>
</th>
</tr>
<tr>
<td>Open Lineage Foundation</td>
<td><a href="https://openlineage.io/">https://openlineage.io/</a></td>
<td><a href="https://github.com/OpenLineage/OpenLineage">https://github.com/OpenLineage/OpenLineage</a></td>
<td><a href="https://openlineage.slack.com/join/shared_invite/zt-oko79982-4bHHhxTUDQ9KXgQWXyWVxg#/shared-invite/email">Slack</a></td>
</tr>
<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="lineage">Data Fabric</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</th>
</tr>
<tr>
<td>Talend</td>
<td><a href="https://www.talend.com/">https://www.talend.com/</a></td>
<td>N/A</td>
<td></td>
</tr>
<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="lineage">Data Storage Format</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</th>
</tr>
<tr>
<td>Parquet</td>
<td><a href="https://parquet.apache.org/">https://parquet.apache.org/</a></td>
<td><a href="https://github.com/apache/parquet-mr/">https://github.com/apache/parquet-mr/</a></td>
<td><a href="https://the-asf.slack.com/">Slack</a>, <a href="https://twitter.com/ApacheParquet">Twitter</a></td>
</tr>
<tr>
<td>Apache Arrow</td>
<td><a href="https://arrow.apache.org/">https://arrow.apache.org/</a></td>
<td><a href="https://github.com/apache/arrow">https://github.com/apache/arrow</a></td>
<td><a href="https://twitter.com/apachearrow">Twitter</a></td>
</tr>
<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="lineage">SQL Query Engine</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</th>
</tr>
<tr>
<td>Apache Iceberg</td>
<td><a href="https://iceberg.apache.org/">https://iceberg.apache.org/</a></td>
<td><a href="https://github.com/apache/iceberg">https://github.com/apache/iceberg</a></td>
<td><a href="https://apache-iceberg.slack.com/join/shared_invite/zt-tlv0zjz6-jGJEkHfb1~heMCJA3Uycrg#/shared-invite/email">Slack</a></td>
</tr>
<tr>
<td>Trino</td>
<td><a href="https://trino.io/">https://trino.io/</a></td>
<td><a href="https://github.com/trinodb/trino">https://github.com/trinodb/trino</a></td>
<td><a href="https://trino.io/slack.html">Slack</a>, <a href="https://twitter.com/trinodb">Twitter</a></td>
</tr>
<tr>
<td>Starburst</td>
<td><a href="https://www.starburst.io/">https://www.starburst.io/</a></td>
<td></td>
<td><a href="https://twitter.com/starburstdata">Twitter</a></td>
</tr>
<tr>
<td>Amazon Athena</td>
<td><a href="https://aws.amazon.com/athena">https://aws.amazon.com/athena</a></td>
<td>N/A</td>
<td></td>
</tr>
<tr>
<td class="whitespace-nowrap">Amazon Redshift Spectrum</td>
<td><a href="https://docs.aws.amazon.com/redshift/latest/dg/c-using-spectrum.html">https://docs.aws.amazon.com/redshift/latest/dg/c-getting-started-using-spectrum.html</a></td>
<td>N/A</td>
<td></td>
</tr>
<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="lineage">Data Analytics / Business Intelligence</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</th>
</tr>
<tr>
<td class="whitespace-nowrap">Power BI</td>
<td class="whitespace-nowrap"><a href="https://powerbi.microsoft.com/">https://powerbi.microsoft.com/</a></td>
<td><a href="">N/A</a></td>
<td></td>
</tr>
<tr>
<td class="whitespace-nowrap">Tableau</td>
<td class="whitespace-nowrap"><a href="https://www.tableau.com/">https://www.tableau.com/</a></td>
<td><a href="">N/A</a></td>
<td><a href="https://www.tableau.com/products/trial">Free Trial</a></td>
</tr>
<tr>
<td class="whitespace-nowrap">Looker</td>
<td class="whitespace-nowrap"><a href="https://www.looker.com/">https://www.looker.com/</a></td>
<td><a href="">N/A</a></td>
<td>
</tr>
<tr>
<td class="whitespace-nowrap">Startree</td>
<td class="whitespace-nowrap"><a href="https://www.startree.ai/">https://www.startree.ai/</a></td>
<td><a href="">N/A</a></td>
<td><a href="https://twitter.com/startreedata">Twitter</a>, <a href="https://communityinviter.com/apps/startreedata/startree-community">Slack</a></td>
</tr>
<tr>
<td class="whitespace-nowrap">Azure Data Explorer</td>
<td class="whitespace-nowrap"><a href="https://azure.microsoft.com/en-us/products/data-explorer/">https://azure.microsoft.com/en-us/products/data-explorer/</a></td>
<td><a href="">N/A</a></td>
<td><a href="https://learn.microsoft.com/en-us/azure/data-explorer/">Documentation</a>, <a href="https://learn.microsoft.com/en-us/azure/data-explorer/kusto/api/">API</a>, <a href="https://learn.microsoft.com/en-us/azure/data-explorer/ingestion-supported-formats">Data Formats</a></td>
</tr>

<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="management">Data Visualization</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</th>
</tr>

<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="management">Data Management</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</th>
</tr>
<tr>
<td>DataOps (Snowflake)</td>
<td><a href="https://www.dataops.live/">https://www.dataops.live/</a></td>
<td><a href=""></a></td>
<td><a href="https://www.dataops.live/dataops-for-dummies-download">eBook</a>, <a href="https://www.dataops.live/dataops-free-trial">Free Trial</a></td>
</tr>

<tr>
<td>Apache Calcite</td>
<td><a href="https://calcite.apache.org/">https://calcite.apache.org/</a></td>
<td></td>
<td><a href="https://twitter.com/ApacheCalcite">Twitter</a></td>
</tr>
<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="datastore">OLAP Data Store</h2>
</th>
</tr>
<tr>
<th>Product</th>
<th>Website</th>
<th>Open Source</th>
<th>Other References</th>
</th>
</tr>
<tr>
<td>Apache Druid</td>
<td><a href="https://druid.apache.org/">https://druid.apache.org/</a></td>
<td><a href="https://github.com/apache/druid/">https://github.com/apache/druid/</a></td>
<td><a href="https://twitter.com/druidio">https://twitter.com/druidio</a></td>
</tr>
<tr>
<td>Apache Pinot</td>
<td><a href="https://pinot.apache.org/">https://pinot.apache.org/</a></td>
<td><a href="https://github.com/apache/pinot">https://github.com/apache/pinot</a></td>
<td><a href="https://twitter.com/ApachePinot">Twitter</a></td>
</tr>
<tr>
<td>Clickhouse</td>
<td><a href="https://clickhouse.com/">https://clickhouse.com/</a></td>
<td><a href="https://github.com/ClickHouse/ClickHouse">https://github.com/ClickHouse/ClickHouse</a></td>
<td><a href="https://twitter.com/ClickhouseDB">https://twitter.com/ClickhouseDB</a></td>
</tr>
<tr>
<td>SingleStore</td>
<td><a href="https://www.singlestore.com/">https://www.singlestore.com/</a></td>
<td><a href="https://github.com/memsql/">https://github.com/memsql/</a></td>
<td></td>
</tr>

<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="datastore">NoSQL Database</h2>
</th>
</tr>
<tr>
<td>Asure Cosmos DB</td>
<td><a href="https://azure.microsoft.com/products/cosmos-db/">https://azure.microsoft.com/products/cosmos-db/</a>
<td>N/A</td>
<td></td>
</tr>

<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="datastore">Time-series Database</h2>
</th>
</tr>
<tr>
<td>Timescale</td>
<td><a href="https://www.timescale.com/">https://www.timescale.com/</a></td>
<td><a href="https://github.com/timescale/timescaledb">https://github.com/timescale/timescaledb</a></td>
<td><a href="https://twitter.com/timescaledb?lang=en">Twitter</a>, <a href="https://slack.timescale.com/">Slack</a></td>
</tr>
<tr>
<td>TempoDB</td>
<td><a href="https://tempo-db.com/">https://tempo-db.com/</a></td>
<td>N/A</td>
<td><a href="https://twitter.com/tempodb">Twitter</a></td>
</tr>
<tr>
<td>M3</td>
<td><a href="https://m3db.io/">https://m3db.io/</a></td>
<td><a href="https://github.com/m3db/m3">https://github.com/m3db/m3</a></td>
<td><a href="https://m3db.slack.com/join/shared_invite/enQtNzE1MTg3MzAxMjM0LWZiYzYzOTM2OTE1ZWMyMjliMzA0NDE1OWQ0MjM5YjA0MzJiMWFkYmFkZWFlZjhlMmU1OGNmZTg2YzNkM2ExYjA#/shared-invite/email">Slack</a></td>
</tr>

<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="datastore">Data Lake / Data Lakehouse</h2>
</th>
</tr>
<tr>
<td>Databricks</td>
<td><a href="https://www.databricks.com/">https://www.databricks.com/</a></td>
<td>N/A</td>
<td><a href="https://twitter.com/databricks">Twitter</a></td>
</tr>
<tr>
<td>Dremio</td>
<td><a href="https://www.dremio.com/">https://www.dremio.com/</a></td>
<td>N/A</td>
<td>Includes <a href="https://www.dremio.com/pricing/">Free Standard Edition</a> </td>
</tr>

<tr>
<th colspan="4" class="text-left text-xl font-bold text-dark m-8 pt-10 pb-5">
<h2 id="datastore">Reverse ETL</h2>
<tr>
<td>Census</td>
<td><a href="https://www.getcensus.com/">https://www.getcensus.com/</a></td>
<td>N/A</td>
<td>Includes <a href="https://www.getcensus.com/pricing">Free Edition</a> </td>
</tr>
</th>
</tr>
</table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- ====== Section End ====== -->

