

    <!-- ====== Content Start ====== -->
    <!-- ====== Hero Section Start ====== -->
    <div id="home" class="relative overflow-hidden bg-primary pt-[120px] md:pt-[130px] lg:pt-[160px]" >
      <div class="container">
        <div class="-mx-4 flex flex-wrap items-center">
          <div class="w-full px-4">
            <div class="hero-content wow fadeInUp mx-auto max-w-[780px] text-center" data-wow-delay=".2s" >
              <h1 class="mb-8 text-3xl font-bold leading-snug text-white sm:text-4xl sm:leading-snug md:text-[45px] md:leading-snug" >
                Data Terminology
              </h1>
              <p class="mx-auto mb-100 max-w-[600px] text-base text-[#e4e4e4] sm:text-lg sm:leading-relaxed md:text-xl md:leading-relaxed" >
              Covering roles and responsibilites, disciplines and topics, data storage approaches, terms and abbreviations.
              </p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- ====== Hero Section End ====== -->

    <!-- ====== Columns Section Start  ======-->
    <section id="_id" class="pt-20 pb-8 lg:pt-[20px] lg:pb-[20px]">
      <div class="container">
        <div class="-mx-4 flex flex-wrap">
          <div class="w-full px-4">
            <div class="max-w-[620px]">
              <h2 class="text-3xl font-bold text-dark" >
                Data Roles
              </h2>
            </div>
          </div>
        </div>
        <div class="-mx-4 flex flex-wrap">
          <div class="w-full px-4 md:w-1/2 lg:w-1/4">
            <div class="wow fadeInUp group mb-12 bg-white" data-wow-delay=".1s">
              <p class="mb-8 text-body-color lg:mb-11">
              <h4 class="mb-3 text-xl font-bold text-dark">
                Modern Data Department
              </h4>
              <ul>
              <li>Data Steward</li>
              <li>Data Custodian</li>
              <li>Data Privacy Officer</li>
              <li>Data Strategist</li>
              <li>Head of Data</li>
              <li>VP of Data Strategy</li>
              <li>Chief Data Officer (CDO)</li>
              <li>Executive Data Sponsor</li>
              </ul>
              </p>
            </div>
          </div>
          <div class="w-full px-4 md:w-1/2 lg:w-1/4">
            <div class="wow fadeInUp group mb-12 bg-white" data-wow-delay=".1s">
              <p class="mb-8 text-body-color lg:mb-11">
              <h4 class="mb-3 text-xl font-bold text-dark">
                Modern Data Team
              </h4>
              <ul>
              <li>Data Architect</li>
              <li>Data Scientist</li>
              <li>Data Engineer</li>
              <li>DataOps Engineer</li>
              <li>Data Science Engineer</li>
              <li>Data Quality Engineer</li>
              <li>Data Security Engineer</li>
              <li>ML Engineer</li>
              <li>Data Specialist</li>
              <li>Data Science Manager</li>
              </ul>
              </p>
            </div>
          </div>
          <div class="w-full px-4 md:w-1/2 lg:w-1/4">
            <div class="wow fadeInUp group mb-12 bg-white" data-wow-delay=".1s">
              <p class="mb-8 text-body-color lg:mb-11">
              <h4 class="mb-3 text-xl font-bold text-dark">
                Traditional Data Engineering
              </h4>
              <ul>
              <li>Data Analyst</li>
              <li>Data Warehouse Developer</li>
              <li>Software Developer</li>
              <li>Software Engineer</li>
              <li>Enterprise Architect</li>
              <li>Solutions Architect</li>
              <li>Data Modeler</li>
              </ul>
              </p>
            </div>
          </div>
          <div class="w-full px-4 md:w-1/2 lg:w-1/4">
            <div class="wow fadeInUp group mb-12 bg-white" data-wow-delay=".1s">
              <p class="mb-8 text-body-color lg:mb-11">
              <h4 class="mb-3 text-xl font-bold text-dark">
                Traditional Data Operations
              </h4>
              <ul>
              <li>DevOps Engineer</li>
              <li>Site Reliability Engineer (SRE)</li>
              <li>Database Reliability Engineer (DBRE)</li>
              <li>Database Administrator (DBA)</li>
              </ul>
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- ====== Columns Section End -->

    <!-- ====== Columns Section Start  ======-->
    <section id="_id" class="pt-20 pb-8 lg:pt-[20px] lg:pb-[20px]">
      <div class="container">
        <div class="-mx-4 flex flex-wrap">
          <div class="w-full px-4">
            <div class="max-w-[620px]">
              <h2 class="text-3xl font-bold text-dark" >
                Data Disciplines
              </h2>
            </div>
          </div>
        </div>
        <div class="-mx-4 flex flex-wrap">
          <div class="w-full px-4 md:w-1/2 lg:w-1/4">
            <div class="wow fadeInUp group mb-12 bg-white" data-wow-delay=".1s">
              <p class="mb-8 text-body-color lg:mb-11">
              <ul>
              <li>Meta Data Management</li>
              <li>Master Data Management (MDM)</li>
              <li>Reference Data Management</li>
              <li>Data Catalog</li>
              <li>Data Governance</li>
              <li>Data Contract</li>
              <li>Data Stewardship</li>
              <li>Data Security</li>
              <li>Data Quality</li>
              <li>Data Lineage</li>
              <li>Data in Motion</li>
              <li>Data Insight</li>
              <li>Data-Driven Decision</li>
              </ul>
              </p>
            </div>
          </div>
          <div class="w-full px-4 md:w-1/2 lg:w-1/4">
            <div class="wow fadeInUp group mb-12 bg-white" data-wow-delay=".1s">
              <p class="mb-8 text-body-color lg:mb-11">
              <ul>
              <li>Data Standards</li>
              <li>Data Privacy</li>
              <li>Data Curation</li>
              <li>Data Science</li>
              <li>Data Workflow</li>
              <li>Data Pipelines</li>
              <li>Data Cleansing</li>
              <li>Data Mapping</li>
              <li>Data Integration</li>
              <li>Data Transformation</li>
              <li>Data Monetization</li>
              </ul>
              </p>
            </div>
          </div>
          <div class="w-full px-4 md:w-1/2 lg:w-1/4">
            <div class="wow fadeInUp group mb-12 bg-white" data-wow-delay=".1s">
              <p class="mb-8 text-body-color lg:mb-11">
              <ul>
              <li>Data Taxonomy</li>
              <li>Data Ontology</li>
              <li>Data Modeling</li>
              <li>Data Analysis</li>
              <li>Business Intelligence (BI)</li>
              <li>Data Analytics</li>
              <li>Data Migration</li>
              <li>Data Archaeology</li>
              <li>Decision Intelligence (DI)</li>
              </ul>
              </p>
            </div>
          </div>
          <div class="w-full px-4 md:w-1/2 lg:w-1/4">
            <div class="wow fadeInUp group mb-12 bg-white" data-wow-delay=".1s">
              <p class="mb-8 text-body-color lg:mb-11">
              <ul>
              <li>Data Store</li>
              <li>Data Stream</li>
              <li>Data Visualization</li>
              <li>Data Storytelling</li>
              <li>Data Dashboard</li>
              <li>Data Observability</li>
              <li>Data Engineering</li>
              <li>Data Agility</li>
              <li>Data Literacy</li>
              <li>Data Gravity</li>
              </ul>
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- ====== Columns Section Start  ======-->
    <section id="_id" class="pt-20 pb-8 lg:pt-[20px] lg:pb-[20px]">
      <div class="container">
        <div class="-mx-4 flex flex-wrap">
          <div class="w-full px-4">
            <div class="max-w-[620px]">
              <h2 class="text-3xl font-bold text-dark" >
                Data Storage
              </h2>
            </div>
          </div>
        </div>
        <div class="-mx-4 flex flex-wrap">
          <div class="w-full px-4 md:w-1/2 lg:w-1/4">
            <div class="wow fadeInUp group mb-12 bg-white" data-wow-delay=".1s">
              <h4 class="mb-3 text-xl font-bold text-dark">
                Database Architectures
              </h4>
              <p class="mb-8 text-body-color lg:mb-11">
              <ul>
              <li>Database</li>
              <li>Data Warehouse (DW) (DWH)</li>
              <li>Data Mart</li>
              <li>Data Lake</li>
              <li>Data LakeHouse</li>
              <li>Data Swamp</li>
              <li>Data Silo</li>
              <li>Data Mesh</li>
              <li>Data Hub</li>
              <li>Big Data</li>
              <li>Data File</li>
              <li>Data Set</li>
              </ul>
              </p>
            </div>
          </div>
          <div class="w-full px-4 md:w-1/2 lg:w-1/4">
            <div class="wow fadeInUp group mb-12 bg-white" data-wow-delay=".1s">
              <h4 class="mb-3 text-xl font-bold text-dark">
                Databases
              </h4>
              <p class="mb-8 text-body-color lg:mb-11">
              <ul>
              <li>Relational Database Management System (RDBMS)</li>
              <li>NoSQL Database</li>
              <li>Key/Value Database</li>
              <li>In Memory Database</li>
              <li>Document Database</li>
              <li>Graph Database</li>
              <li>Timeseries Database</li>
              <li>Ledger Database</li>
              <li>Column-oriented Database</li>
              <li>Object-oriented Database</li>
              </ul>
              </p>
            </div>
          </div>
          <div class="w-full px-4 md:w-1/2 lg:w-1/4">
            <div class="wow fadeInUp group mb-12 bg-white" data-wow-delay=".1s">
              <h4 class="mb-3 text-xl font-bold text-dark">
                Data Terms
              </h4>
              <p class="mb-8 text-body-color lg:mb-11">
              <ul>
              <li>Data Structure</li>
              <li>Data Query Language</li>
              <li>Structured Query Language (SQL)</li>
              <li>Extract, Transform, Load (ETL)</li>
              <li>Extract, Load, Transform (ELT)</li>
              <li>Change Data Capture (CDC)</li>
              <li>Atomicity, Consistency, Isolation, Durability (ACID)</li>
              <li>Online Transactional Processing (OLTP)</li>
              <li>Online Analytical Processing (OLAP)</li>
              <li>NoSQL</li>
              <li>Machine Learning (ML)</li>
              <li>Artifical Intelligence (AI)</li>
              <li>Single Source of Truth (SSOT)</li>
              </p>
            </div>
          </div>
          <div class="w-full px-4 md:w-1/2 lg:w-1/4">
            <div class="wow fadeInUp group mb-12 bg-white" data-wow-delay=".1s">
              <h4 class="mb-3 text-xl font-bold text-dark">
                Cool Project Terms
              </h4>
              <p class="mb-8 text-body-color lg:mb-11">
              <ul>
              <li>Digital Garden</li>
              </ul>
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- ====== Columns Section End -->
